version: "3.4"

services:
  redis:
    image: redis:5.0.5
    ports:
      - "6401:6379"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=audionekt_admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=audionekt
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=audionekt@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=audionekt
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  database-data:
  pgadmin:
