# docker-compose build
version: "3.0"
volumes:
  postgis-data:
  pgadmin:

services:
  redis:
    image: redis:5.0.5
    ports:
      - "6401:6379"
    restart: always

  postgis:
    image: kartoza/postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASSWORD}
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
